

name: Deploy to AWS

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'
      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: MyStack
          template: SNSFormation.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            topicName=exampletopic,
            displayName=CMNCompany
        

